
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.5'

_lr_method = 'LALR'

_lr_signature = '9195A5F7E05E627AC0F404F95AEB41BA'
    
_lr_action_items = {'$end':([1,2,4,5,13,14,15,16,17,18,19,20,],[-2,-10,0,-9,-10,-7,-3,-5,-4,-6,-1,-8,]),')':([5,12,13,14,15,16,17,18,20,],[-9,20,-10,-7,-3,-5,-4,-6,-8,]),'-':([0,1,2,3,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,],[6,9,-10,6,-9,6,6,6,6,6,6,9,-10,-7,-3,-5,-4,-6,9,-8,]),'NAME':([0,3,6,7,8,9,10,11,],[2,13,13,13,13,13,13,13,]),'(':([0,3,6,7,8,9,10,11,],[3,3,3,3,3,3,3,3,]),'/':([1,2,5,12,13,14,15,16,17,18,19,20,],[10,-10,-9,10,-10,-7,10,-5,10,-6,10,-8,]),'+':([1,2,5,12,13,14,15,16,17,18,19,20,],[7,-10,-9,7,-10,-7,-3,-5,-4,-6,7,-8,]),'=':([2,],[11,]),'NUMBER':([0,3,6,7,8,9,10,11,],[5,5,5,5,5,5,5,5,]),'*':([1,2,5,12,13,14,15,16,17,18,19,20,],[8,-10,-9,8,-10,-7,8,-5,8,-6,8,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[4,]),'expression':([0,3,6,7,8,9,10,11,],[1,12,14,15,16,17,18,19,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> NAME = expression','statement',3,'p_statement_assign','calc.py',55),
  ('statement -> expression','statement',1,'p_statement_expr','calc.py',59),
  ('expression -> expression + expression','expression',3,'p_expression_binop','calc.py',63),
  ('expression -> expression - expression','expression',3,'p_expression_binop','calc.py',64),
  ('expression -> expression * expression','expression',3,'p_expression_binop','calc.py',65),
  ('expression -> expression / expression','expression',3,'p_expression_binop','calc.py',66),
  ('expression -> - expression','expression',2,'p_expression_uminus','calc.py',73),
  ('expression -> ( expression )','expression',3,'p_expression_group','calc.py',77),
  ('expression -> NUMBER','expression',1,'p_expression_number','calc.py',81),
  ('expression -> NAME','expression',1,'p_expression_name','calc.py',85),
]
